name: Node.js CI
on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        node: [10.x, 12.x, 14.x, 16.x, 18.x, 20.x, 22.x, 24.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
